/*
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Query
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-21T16:32:46.492Z")
public class Query {
  @SerializedName("timeperiods")
  private List<String> timeperiods = new ArrayList<String>();

  @SerializedName("query")
  private List<String> query = new ArrayList<String>();

  public Query timeperiods(List<String> timeperiods) {
    this.timeperiods = timeperiods;
    return this;
  }

  public Query addTimeperiodsItem(String timeperiodsItem) {
    this.timeperiods.add(timeperiodsItem);
    return this;
  }

   /**
   * List of periods to query
   * @return timeperiods
  **/
  @ApiModelProperty(required = true, value = "List of periods to query")
  public List<String> getTimeperiods() {
    return timeperiods;
  }

  public void setTimeperiods(List<String> timeperiods) {
    this.timeperiods = timeperiods;
  }

  public Query query(List<String> query) {
    this.query = query;
    return this;
  }

  public Query addQueryItem(String queryItem) {
    this.query.add(queryItem);
    return this;
  }

   /**
   * String list of query statements
   * @return query
  **/
  @ApiModelProperty(required = true, value = "String list of query statements")
  public List<String> getQuery() {
    return query;
  }

  public void setQuery(List<String> query) {
    this.query = query;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Query query = (Query) o;
    return Objects.equals(this.timeperiods, query.timeperiods) &&
        Objects.equals(this.query, query.query);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeperiods, query);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Query {\n");
    
    sb.append("    timeperiods: ").append(toIndentedString(timeperiods)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

